/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Column: typeof import('primevue/column')['default']
    Datatable: typeof import('primevue/datatable')['default']
    DataTable: typeof import('primevue/datatable')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    InputEl: typeof import('./src/components/InputEl.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    SelectEl: typeof import('./src/components/SelectEl.vue')['default']
    TableEl: typeof import('./src/components/TableEl.vue')['default']
    TableSearch: typeof import('./src/components/TableSearch.vue')['default']
    TableSearchEl: typeof import('./src/components/TableSearchEl.vue')['default']
    Time: typeof import('./src/components/Time.vue')['default']
    TimeEl: typeof import('./src/components/TimeEl.vue')['default']
    UseElementsLogic: typeof import('./src/components/composables/useElementsLogic.vue')['default']
  }
}
